image: node:lts
before_script:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store
pages:
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  script:
    - pnpm install
    - pnpm build --outDir public
  artifacts:
    paths:
      - public
  only:
    - main
